### ISSUE TITLE
Debian 10 for container image

### ISSUE THREAD

**Issue by mavit** [LMS-Community/slimserver-platforms#14]
The container image is currently based on Debian 9, but the Debian project [describe version 9 as “end of life”](https://wiki.debian.org/DebianReleases).  Do we know if anything prevents us from using Debian 10?

**Comment by mherger** [comment]
The reason why I chose v9 is that we have all the required binaries in LMS already. I hate building more if there's no/little demand. And as a Docker container is pretty much self-contained and running just one task, I believe we can live with this "risk" and move on as soon as we have more recent binaries available anyway.

**Comment by mwaltersbmc** [comment]
I think the choice of Debian 9 is the cause of this problem with sox/wvunpack

https://forums.slimdevices.com/showthread.php?111828-Official-docker-container-for-LMS&p=1010271&viewfull=1#post1010271

It looks like the aarch64 sox/wvunpack binaries are built with a later glibc.

**Comment by mherger** [comment]
As I wrote in that thread we moved to Debian 10 for LMS 8.2, as you suggested in your edit (sorry, didn't see it, as I don't get edits via mail).
