### ISSUE TITLE
manifest unknown?

### ISSUE THREAD

**Issue by dg1sek** [LMS-Community/slimserver-platforms#17]
I am experiencing a strange issue with upgrading to the latest version with docker-compose (manual pull of container works).

```
dg1sek@raspberrypi:/opt$ docker-compose pull lms
Pulling lms ... error

ERROR: for lms  manifest for lmscommunity/logitechmediaserver:latest not found: manifest unknown: manifest unknown
ERROR: manifest for lmscommunity/logitechmediaserver:latest not found: manifest unknown: manifest unknown
```

my **docker-compose.yaml**:

```
  lms:
    container_name: lms
    image: lmscommunity/logitechmediaserver
    ports:
      - "9000:9000/tcp"
      - "9090:9090/tcp"
      - "3483:3483/tcp"
      - "3483:3483/udp"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/timecapsuleSSD/Music:/music:ro
      - /opt/squeezebox-config:/config:rw
      - /opt/squeezebox-playlist:/playlist:rw
    restart: always
```

**Comment by mherger** [comment]
Hmm... I don't see where you're referencing `latest`. I guess it's what you used when you downloaded the image initially. But yes, I stopped publishing that tag because it caused issues. Please get `8.0.1-dev` or `8.1.0-dev` instead. See https://hub.docker.com/r/lmscommunity/logitechmediaserver/tags?page=1&ordering=last_updated for available tags.

**Comment by dg1sek** [comment]
Thanks, that's what I thought. I guess "latest" is just the default.

If I add "8.1.0-dev" to it, then doesn't that somehow break the whole concept of automatically moving to the latest version?
Or do you plan to never change that version number?

**Comment by michaelherger** [comment]
As long as there's the `-dev` appendix this is a moving target. There can be daily changes, or more than daily. Only once it's `8.1.0` alone it's "released" and doesn't get any updates any more. Next up would be `8.1.1-dev` for bugfix releases.

**Comment by mherger** [comment]
This should be resolved by now. I changed the way we tag images.
