### ISSUE TITLE
Players lost after container restart

### ISSUE THREAD

**Issue by mvl64** [LMS-Community/slimserver-platforms#31]
I'm running LMS in a docker container on a synology NAS.
There are a couple of players (BOOM) connected to LMS, and all is working well - until I restart the container:

After the restart, no players are known on LMS (when using the web UI).
When I start the players they have to go through initial setup - long press ON to restart the player which will then go through setup (getting IP address, searching for the server, etc).

Is this expected behavior, or does this point to a configuration error ?
If the latter, is there a recommended way to prevent losing the "connected players"?

**Comment by mherger** [comment]
Did you correctly configure the ports, in particular 3483 tcp AND udp? The players are using these to discover LMS.

**Comment by mvl64** [comment]
Hi, sorry for the delay - I lost the thread to this issue.

Yes, the port is open on TCP and UDP.
See below screenshot for your reference.

Note: The players can find the server fine until the container is restarted - after that they have to go through "initial network setup" again, so getting ip addres, ... and finally discovering the server.
The discovery goes without problems, it's just that a discovery and setup is required; whereas it is not while the container keeps running (I have it up for weeks without any issue).

![image](https://user-images.githubusercontent.com/42496758/150145650-4f7afa1c-9f78-4907-b7f7-a677393a590d.png)

**Comment by mvl64** [comment]
It seems the player information on the server is lost upon restarting the container.
Before restart can see two players connected - both in the server settings/information tab and in the player selection on the main screen:
 
![image](https://user-images.githubusercontent.com/42496758/150531357-90fa584b-0a41-46fc-ba6b-44b35b162141.png)

After I restart the container, both items are empty:
![image](https://user-images.githubusercontent.com/42496758/150531435-97e5dab3-9739-415c-9458-6a26e3e11523.png)

Where is the player information stored on the server ? I was expecting somewhere in the /config tree, which is stored in a host volume, but that does not seem the case.

**Comment by michaelherger** [comment]
The player would only show up if they were connected to the server. Can you connect them (using the player's UI)?

**Comment by mvl64** [comment]
Yes, I can - that's my point: why do they disappear after the container has been restarted ?

**Comment by mherger** [comment]
You shouldn't have to hard reboot the players. That's definitely not expected behaviour. Usually using the remote or the controls on the device itself should make it re-connect, or try to re-connect at least. Does that really not work? What happens when you want to navigate the menus in that disconnected state?

**Comment by mvl64** [comment]
After I restart the container, the player stops responding to the power button (so I just reset the player).
I never tried the other controls, but because of your question I tried to turn the knob; and this brought up new behaviour:
the player reports "server disconnected", and suggests to press the back button to re-connect.
When I do, the player still remembers the server IP and allows me to quickly reconnect.
So, no hard reset is required, you're right :).

This reduces the significance of the problem quite a bit - this is not a big deal.
It would be interesting to find a way for this to not happen though - before I ran LMS in a container I had it running as a native app on my Synology NAS, which I rebooted occasionally too, but the server didn't lose the player details then - so it seems this information is stored in a file on the server somewhere. Do you know where this would be ?

(I'd like to try adding another volume to persistently store the player details on the server.)

**Comment by michaelherger** [comment]
Why don't you ask on forums.slimdevices.com? There are many more Docker users (I'm none of them) who might have dealt with this before.
