### ISSUE TITLE
How to use port 5353 UDP on Synology?

### ISSUE THREAD

**Issue by phqzgunsfjror** [LMS-Community/slimserver-platforms#32]
Hi,

does somebody know how I can run lms with port 5353 UDP on Synology?
I would need that in order to run Spotty (Spotifiy Plugin) properly...

Error message: "Local port 5353, ... conflicts with other ports used by other services"

It seems the port 5353 UDP is already in usage by avahi-daemon:
```
sudo netstat -tulpn | grep 5353
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           7500/avahi-daemon:
```

I stopped/disabled avahi...
```
sudo synoservice --stop avahi
```
... and I can confirm its not running anymore - even after a restart of the NAS. And the port is not in usage either.
Still same error message that the port is already in usage.

**Comment by michaelherger** [comment]
I think DSM does reserve some ports it's using even when the service is shut down. I've seen similar behavior with LMS' port 9002 which wasn't available as long as the old package had not been uninstalled. Even when it did not run, that port was not available to the container.

As it's unlikely you'll want to uninstall avahi support, there's probably little you can do. Unless you figure out how to somehow expose Spotty's information using DSM's avahi. But don't ask me how that would work.

In any case: you should post to https://forums.slimdevices.com. This repository is definitely not the right place to ask this kind of question.
