### ISSUE TITLE
Cannot connect to github lugin repository even impelemented with proxy

### ISSUE THREAD

**Issue by wswv** [LMS-Community/slimserver-platforms#33]
Hi, I found a issue, when I use docker-compose to start the docker, everything looks fine except the plugin report:

Bad repository https://github.com/LMS-Community/lms-plugin-repository/raw/master/extensions.xml - Connect timed out: Resource temporarily unavailable

I understand it should be blocked by ISP, so I tried to use proxy to solve it. but even I configured proxy in web configuration-advance-network. it can not work. i tried to put the proxy in environment of docker-compose,
```
    environment:
      - http_proxy=http://192.168.1.11:1234
      - https_proxy=http://192.168.1.11:1234
```

 I tried to use curl to test it, it looks OK, but still the system report:
Bad repository https://github.com/LMS-Community/lms-plugin-repository/raw/master/extensions.xml - Connect timed out:

Could someone give some support about it, thanks!

**Comment by michaelherger** [comment]
Hi there - a few questions:

* you say "when I used docker-compose": does that mean without docker-compose it would work?
* "everything looks fine": would internet radio work?
* "I understand it should be blocked": I don't understand. Why should it be?
* Please enter the proxy's IP address in LMS _without_ the http://, just the IP address and port

You could enable debug logging for `network.asynchttp` to get more information in the log file. It would tell you whether it was picking up the proxy or not.

**Comment by wswv** [comment]
Hi, Michael,

Thanks for your feedback!

Purpose to remove affect of the setting in dockker-compose, I remove non-normal setting in docker-compose(add proxy in environment). add proxy in setting->Advance->Web Proxy like: 192.168.1.11:1234. then I tried to grab some log like below(according to your guidance):

[lms_log.txt](https://github.com/Logitech/slimserver-platforms/files/7976074/lms_log.txt)


- you say "when I used docker-compose": does that mean without docker-compose it would work?
 -- I don't test it, I just use docker-compose to test it.
- "everything looks fine": would internet radio work?
 -- it means the web interface, it could scan file. I don't test radio work. from the log, the radio looks can not work.
- "I understand it should be blocked": I don't understand. Why should it be?
 -- I tried the link: https://github.com/LMS-Community/lms-plugin-repository/raw/master/extensions.xml in browser, it can not open, but it could open with proxy in browser.
-  Please enter the proxy's IP address in LMS without the http://, just the IP address and port
 -- yes, I grab log with your advise.

**Comment by michaelherger** [comment]
Thanks for the log - that should be useful. What I'm seeing is that the proxied connection works fine. Proxy is being used, and response from GitHub.com received. That response would be a redirection to https://raw.githubusercontent.com/LMS-Community/lms-plugin-repository/master/extensions.xml. Unfortunately it's that second URL which fails to load. It seems that your DNS would not return an IP address for it:

```
[22-02-01 13:11:45.8937] Slim::Networking::Async::DNS::__ANON__ (58) Lookup failed for raw.githubusercontent.com
```

Are you using some particular DNS for the name resolution? Can you open the above URL in a browser? Would that browser be using the same DNS as LMS?

**Comment by wswv** [comment]
Hi, Michael,

I tried the link: raw.githubusercontent.com, it jump to https://github.com/ with proxy in browser. it can not open without proxy in browser.

I tried to restart the docker and check proxy log, find there is no access log of raw.githubusercontent.com. it only has opml.radiotime.com record from the lms activities.  then I tried access raw.githubusercontent.com from web browser with proxy, I can find the raw.githubusercontent.com in proxy log. 

if it happened due to DNS. I should find the access log in proxy log. then I tried to update my other docker image by watch tower. it will access githubusercontent.com. I saw some log pkg-containers.githubusercontent.com in proxy log.






By the way, my OS used for LMS is Debian burster. I tried to install Perl SSL package according to https://forums.slimdevices.com/showthread.php?103728.
```
 sudo apt-get install libio-socket-ssl-perl libnet-ssleay-perl
```
It installed and there is no error report.

But all these installed and the issue still duplicated even I reboot total system.

**Comment by michaelherger** [comment]
> if it happened due to DNS. I should find the access log in proxy log

No, if DNS lookup failed, the server wouldn't even try to reach out to the host, thus wouldn't come by the proxy. Please double check the container's DNS/network configuration.

**Comment by wswv** [comment]
Yesterday I tried it on raspibian with docker deploy, it could connect to the plugin site(Could access the link: https://raw.githubusercontent.com/LMS-Community/lms-plugin-repository/master/extensions.xml), then I can find new plugin list and install plugin by myself. 

Thanks for your support! it looks like the issue caused by openmedialvalut 5.

**Comment by wswv** [comment]
Solved by add DNS server in docker-compose file.
```yaml

services:
  lms:
    container_name: lms
    image: lmscommunity/logitechmediaserver
    dns:
      - 8.8.8.8
      - 4.4.4.4
```
