### ISSUE TITLE
"latest" image on Docker Hub isn't

### ISSUE THREAD

**Issue by ipilcher** [LMS-Community/slimserver-platforms#35]
The image tagged as `latest` on [Docker Hub](https://hub.docker.com/r/lmscommunity/logitechmediaserver/tags) appears to actually be 8.2.0.  Not sure what version it's supposed to be, but I'm pretty sure that's not it.

**Comment by michaelherger** [comment]
Please see the descriptions of `latest`, `stable`, and `dev` on https://hub.docker.com/r/lmscommunity/logitechmediaserver. 8.2.0 indeed is the latest released version.
