### ISSUE TITLE
Point LMS to a different subnet with wifi devices on it?

### ISSUE THREAD

**Issue by NonaSuomy** [LMS-Community/slimserver-platforms#37]
Does anyone know how to point Logitech Media Server (docker) 10.42.42.* at a different IP range (wifi) 10.13.37.* where the squeeze player exists?

Thank you.

**Comment by mherger** [comment]
Please post to forums.slimdevices.com. This is not a LMS issue.

**Comment by NonaSuomy** [comment]
This is an LMS issue. I searched the forum and nobody in the forums seems to know the answer. Besides directly pointing the media devices at the server, is there a way to tell LMS what network to auto-search for media devices?

**Comment by auberginepop** [comment]
Can you use `network_mode: host` and then make sure the docker host has an interface on the same subnet as the devices.

**Comment by michaelherger** [comment]
> This is an LMS issue. Nobody in the forums knows the answer. Beside directly pointing the media devices at the server, is there a way to tell LMS what network to auto search for media devices?

Can you point me to the thread you asked this in?

**Comment by NonaSuomy** [comment]
Sorry, I fixed the wording above I meant I searched the forum and found nothing about auto-finding multiple subnet configurations. I just posted the question now.

https://forums.slimdevices.com/showthread.php?116947-LMS-on-a-different-network-than-clients&p=1063117#post1063117

Thanks.
