### ISSUE TITLE
Secret(s) found: 2 - [Product Security - Secret Scanning]

### ISSUE THREAD

**Issue by nhamzi** [LMS-Community/slimserver-platforms#39]
This is automated issue created by Logitech Secret Scanner v1.0 - Nabil Hamzi

It seems that information looking like a secret (password, token, credentials, ...) has been identified in this github repository.
We should avoid as much as possible to store secrets in Github code repository. Github has an 'encrypted secrets' feature for this.
Please react on this thread with @nhamzi for any question.

Here are the findings, SecretLink contains the link to the sensitive value to be renewed, refreshed and deleted.

SecretLink=https://github.com/Logitech/slimserver-platforms/blob/2bb2489d488474d08d4522cb065d451c520e7354/win32/WHS Add-In/SqueezeCenter/SettingsTabUserControl.resx#L132-L132
SecretLink=https://github.com/Logitech/slimserver-platforms/blob/e14655ab3031cf10f7ce128d389e4ccb4dc70925/win32/WHS Add-In/SqueezeCenter/Properties/Resources.resx#L120-L120

**Comment by etissotdupont** [comment]
@mherger , can you please take care of this one?

**Comment by michaelherger** [comment]
Yeah, I got _hundreds_ of such findings to go through... the above two are false positives anyway. Maybe we should remove you from these repositories?

**Comment by etissotdupont** [comment]
@michaelherger, Yes, you can remove me from all SB related repos. But @nhamzi should find a way to point the issue those to *one* owner per issue. Otherwise this is going to turn a garden variety nightmare into a hellish life of pain with no end in sight.

**Comment by nhamzi** [comment]
@etissotdupont I cannot assign issue to one single owner. First because I don't have rights to do so (this can be solved, I think ...), second I don't know who to assign the issue.

For your information, I will never report a finding twice. So for false positives, the issue can be closed with a comment.

**Comment by mherger** [comment]
These are UI element identifiers, not secrets.
