### ISSUE TITLE
rename the initscripts back to squeezeboxserver

### ISSUE THREAD

**Issue by eduvik** [LMS-Community/slimserver-platforms#4]
Having the init scripts called logitechmediaserver but every other reference calling it squeezeboxserver is confusing. Can we just call the whole lot squeezeboxserver?

**Comment by mherger** [comment]
It would have made sense not to change it back then. But with tens of thousands of installations today and not a single complaint in years I doubt the idea would find many friends. I do understand that for new users this might be slightly confusing. But the existing users out there will not be outnumbered by new users any time soon.
