### ISSUE TITLE
Is the chown on /lms on startup actually neccessary?

### ISSUE THREAD

**Issue by gtallan** [LMS-Community/slimserver-platforms#52]
I know this just adds a bit of delay during the container startup (as referenced in issue #44) - not a huge problem.

But I wonder why the chown is actually needed as all the file permissions under this path appear to have correct permissions for world read/execute access (and if there was doubt about this, it could be enforced during the container build). Are there any writes expected to this directory?

The LMS container appears to work correctly under a specified uid/gid even if the ownership change to /lms is removed.

Apologies if this is a naive question, I might be missing something!

**Comment by michaelherger** [comment]
Don't know, really. Let's give removing it a try.
