### ISSUE TITLE
EXTRA_ARGS or EXTRA_ARG

### ISSUE THREAD

**Issue by Floriszz** [LMS-Community/slimserver-platforms#70]
In the explanation of below url it is confusion what to use.
In the manual it says; "EXTRA_ARG" for specifying the advertiseaddr parameter, but in the example docker run/compose lines, "EXTRA_ARGS" is used. 
I tried both options for advertiseaddr, and they both seems to work..

[Docker](https://github.com/LMS-Community/slimserver-platforms/tree/HEAD/Docker)

**Comment by michaelherger** [comment]
Thanks for the heads up! Should be fixed in 38b159cb.
